# Basic `dependabot.yml` file with
# minimum configuration for two package managers

version: 2
updates:
  # Enable version updates for npm project
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"
    reviewers:
      - JamsRepos
      - PhantomMantis
      - MrDynamo

  # Enable version updates for poetry backend
  - package-ecosystem: "pip"
    # Look for `pyproject.toml` and `lock` files in the `backend` directory
    directory: "/apps/wizarr_backend/"
    # Check the pip registry for updates every day (weekdays)
    schedule:
      interval: "daily"
    reviewers:
      - JamsRepos
      - PhantomMantis
      - MrDynamo

  # Enable version updates for github actions
  - package-ecosystem: "github-actions"
    # Defaults to .github/workflows directory
    directory: "/"
    # Check the actions registry for updates every day (weekdays)
    schedule:
      interval: "daily"
    reviewers:
      - JamsRepos
      - PhantomMantis
      - MrDynamo